### ISSUE TITLE
Date picker view distorted when using UINavigationController within a UITabBarController.

### ISSUE THREAD

**Issue by cmedinasoriano** [Tuslareb/JBDatePicker#16]
Hi,

I really love this Calendar and I love it uses Swift.  I am trying to add this calendar to a view within a NavigationController which is in turn an item for a TabBarController, but it gets distorted.  The weekview scroller is distorted and shifted upwards (first week hides behind the names of the day) and also scrolls in the vertical direction.  The only way I got this working was creating the TitleBar and navigation buttons without using a UINavigationController.  Is this what was expected or is it a bug?

Thanks again for your time and for this great component.

**Comment by Tuslareb** [comment]
Hi, thanks for your kind words. To answer your question: no, this is not expected behavior and it seems to be a bug. However, my example app also uses JBDatePicker within a UINavigationController within a UITabbarController, so I don't understand what's happening.

It is possible for you to provide me with a sample app that demonstrates the bug? That would make it easier for me to debug.
